# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\ui\modeleditor.ui'
#
# Created: Tue Jan 15 16:55:59 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ModelEditor(object):
    def setupUi(self, ModelEditor):
        ModelEditor.setObjectName(_fromUtf8("ModelEditor"))
        ModelEditor.resize(580, 343)
        ModelEditor.setWindowTitle(QtGui.QApplication.translate("ModelEditor", "Model Editor", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/monokuma-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ModelEditor.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(ModelEditor)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnExtract = QtGui.QToolButton(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExtract.sizePolicy().hasHeightForWidth())
        self.btnExtract.setSizePolicy(sizePolicy)
        self.btnExtract.setText(QtGui.QApplication.translate("ModelEditor", "Extract...  ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExtract.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.btnExtract.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnExtract.setAutoRaise(True)
        self.btnExtract.setObjectName(_fromUtf8("btnExtract"))
        self.horizontalLayout_2.addWidget(self.btnExtract)
        self.btnImport = QtGui.QToolButton(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImport.sizePolicy().hasHeightForWidth())
        self.btnImport.setSizePolicy(sizePolicy)
        self.btnImport.setText(QtGui.QApplication.translate("ModelEditor", "Import...  ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.btnImport.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnImport.setAutoRaise(True)
        self.btnImport.setArrowType(QtCore.Qt.NoArrow)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.horizontalLayout_2.addWidget(self.btnImport)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treePaks = QtGui.QTreeWidget(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treePaks.sizePolicy().hasHeightForWidth())
        self.treePaks.setSizePolicy(sizePolicy)
        self.treePaks.setMinimumSize(QtCore.QSize(112, 0))
        self.treePaks.setMaximumSize(QtCore.QSize(112, 16777215))
        self.treePaks.setAlternatingRowColors(True)
        self.treePaks.setIndentation(15)
        self.treePaks.setRootIsDecorated(False)
        self.treePaks.setUniformRowHeights(True)
        self.treePaks.setAnimated(False)
        self.treePaks.setObjectName(_fromUtf8("treePaks"))
        self.treePaks.headerItem().setText(0, _fromUtf8("Model PAKs"))
        self.horizontalLayout.addWidget(self.treePaks)
        self.treeModels = QtGui.QTreeWidget(ModelEditor)
        self.treeModels.setMinimumSize(QtCore.QSize(164, 0))
        self.treeModels.setMaximumSize(QtCore.QSize(164, 16777215))
        self.treeModels.setAlternatingRowColors(True)
        self.treeModels.setIndentation(15)
        self.treeModels.setUniformRowHeights(True)
        self.treeModels.setObjectName(_fromUtf8("treeModels"))
        self.treeModels.headerItem().setText(0, QtGui.QApplication.translate("ModelEditor", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.treeModels)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblTexName = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTexName.sizePolicy().hasHeightForWidth())
        self.lblTexName.setSizePolicy(sizePolicy)
        self.lblTexName.setMinimumSize(QtCore.QSize(0, 19))
        self.lblTexName.setText(QtGui.QApplication.translate("ModelEditor", "bg_001_p10b1e/0000.gim", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTexName.setObjectName(_fromUtf8("lblTexName"))
        self.horizontalLayout_5.addWidget(self.lblTexName)
        self.label_5 = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText(QtGui.QApplication.translate("ModelEditor", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lblTexSize = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTexSize.sizePolicy().hasHeightForWidth())
        self.lblTexSize.setSizePolicy(sizePolicy)
        self.lblTexSize.setText(QtGui.QApplication.translate("ModelEditor", "1248 bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTexSize.setObjectName(_fromUtf8("lblTexSize"))
        self.horizontalLayout_5.addWidget(self.lblTexSize)
        self.label_6 = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText(QtGui.QApplication.translate("ModelEditor", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lblTexRes = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTexRes.sizePolicy().hasHeightForWidth())
        self.lblTexRes.setSizePolicy(sizePolicy)
        self.lblTexRes.setMinimumSize(QtCore.QSize(0, 19))
        self.lblTexRes.setText(QtGui.QApplication.translate("ModelEditor", "128 x 128", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTexRes.setObjectName(_fromUtf8("lblTexRes"))
        self.horizontalLayout_5.addWidget(self.lblTexRes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.lblTexture = QtGui.QLabel(ModelEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTexture.sizePolicy().hasHeightForWidth())
        self.lblTexture.setSizePolicy(sizePolicy)
        self.lblTexture.setAutoFillBackground(False)
        self.lblTexture.setStyleSheet(_fromUtf8(""))
        self.lblTexture.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTexture.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTexture.setText(_fromUtf8(""))
        self.lblTexture.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTexture.setObjectName(_fromUtf8("lblTexture"))
        self.verticalLayout_2.addWidget(self.lblTexture)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnBGColor = QtGui.QToolButton(ModelEditor)
        self.btnBGColor.setText(QtGui.QApplication.translate("ModelEditor", "Background Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBGColor.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.btnBGColor.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnBGColor.setAutoRaise(False)
        self.btnBGColor.setObjectName(_fromUtf8("btnBGColor"))
        self.horizontalLayout_3.addWidget(self.btnBGColor)
        self.btnClearBG = QtGui.QToolButton(ModelEditor)
        self.btnClearBG.setText(QtGui.QApplication.translate("ModelEditor", "Clear BG", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearBG.setObjectName(_fromUtf8("btnClearBG"))
        self.horizontalLayout_3.addWidget(self.btnClearBG)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(ModelEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.actionExtractAll = QtGui.QAction(ModelEditor)
        self.actionExtractAll.setText(QtGui.QApplication.translate("ModelEditor", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractAll.setObjectName(_fromUtf8("actionExtractAll"))
        self.actionExtractSelected = QtGui.QAction(ModelEditor)
        self.actionExtractSelected.setText(QtGui.QApplication.translate("ModelEditor", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractSelected.setToolTip(QtGui.QApplication.translate("ModelEditor", "Extract Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractSelected.setObjectName(_fromUtf8("actionExtractSelected"))
        self.actionExtractUnique = QtGui.QAction(ModelEditor)
        self.actionExtractUnique.setText(QtGui.QApplication.translate("ModelEditor", "Unique", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExtractUnique.setObjectName(_fromUtf8("actionExtractUnique"))
        self.actionImportTexture = QtGui.QAction(ModelEditor)
        self.actionImportTexture.setText(QtGui.QApplication.translate("ModelEditor", "Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportTexture.setObjectName(_fromUtf8("actionImportTexture"))
        self.actionImportGMO = QtGui.QAction(ModelEditor)
        self.actionImportGMO.setText(QtGui.QApplication.translate("ModelEditor", "GMO Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportGMO.setObjectName(_fromUtf8("actionImportGMO"))
        self.actionImportFull = QtGui.QAction(ModelEditor)
        self.actionImportFull.setText(QtGui.QApplication.translate("ModelEditor", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportFull.setObjectName(_fromUtf8("actionImportFull"))

        self.retranslateUi(ModelEditor)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ModelEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ModelEditor.reject)
        QtCore.QObject.connect(self.btnBGColor, QtCore.SIGNAL(_fromUtf8("clicked()")), ModelEditor.set_background_color)
        QtCore.QObject.connect(self.btnClearBG, QtCore.SIGNAL(_fromUtf8("clicked()")), ModelEditor.clear_background_color)
        QtCore.QObject.connect(self.treePaks, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), ModelEditor.model_pak_selected)
        QtCore.QObject.connect(self.treeModels, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QTreeWidgetItem*,QTreeWidgetItem*)")), ModelEditor.texture_selected)
        QtCore.QMetaObject.connectSlotsByName(ModelEditor)
        ModelEditor.setTabOrder(self.btnExtract, self.btnImport)
        ModelEditor.setTabOrder(self.btnImport, self.treePaks)
        ModelEditor.setTabOrder(self.treePaks, self.treeModels)
        ModelEditor.setTabOrder(self.treeModels, self.btnBGColor)
        ModelEditor.setTabOrder(self.btnBGColor, self.btnClearBG)
        ModelEditor.setTabOrder(self.btnClearBG, self.buttonBox)

    def retranslateUi(self, ModelEditor):
        pass

import icons_rc
