# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\ui\settings.ui'
#
# Created: Mon Dec 17 22:25:43 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsMenu(object):
    def setupUi(self, SettingsMenu):
        SettingsMenu.setObjectName(_fromUtf8("SettingsMenu"))
        SettingsMenu.resize(511, 405)
        SettingsMenu.setWindowTitle(QtGui.QApplication.translate("SettingsMenu", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/monokuma-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsMenu.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(SettingsMenu)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPrefs = QtGui.QWidget()
        self.tabPrefs.setObjectName(_fromUtf8("tabPrefs"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabPrefs)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox.setTitle(QtGui.QApplication.translate("SettingsMenu", "Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(-1, 4, -1, 7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkPlayVoices = QtGui.QCheckBox(self.groupBox)
        self.chkPlayVoices.setText(QtGui.QApplication.translate("SettingsMenu", "Voices", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlayVoices.setChecked(True)
        self.chkPlayVoices.setObjectName(_fromUtf8("chkPlayVoices"))
        self.horizontalLayout_3.addWidget(self.chkPlayVoices)
        self.chkPlayBGM = QtGui.QCheckBox(self.groupBox)
        self.chkPlayBGM.setEnabled(False)
        self.chkPlayBGM.setText(QtGui.QApplication.translate("SettingsMenu", "BGM", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlayBGM.setObjectName(_fromUtf8("chkPlayBGM"))
        self.horizontalLayout_3.addWidget(self.chkPlayBGM)
        self.chkPlaySFX = QtGui.QCheckBox(self.groupBox)
        self.chkPlaySFX.setEnabled(False)
        self.chkPlaySFX.setText(QtGui.QApplication.translate("SettingsMenu", "SFX", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPlaySFX.setObjectName(_fromUtf8("chkPlaySFX"))
        self.horizontalLayout_3.addWidget(self.chkPlaySFX)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsMenu", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkSpellCheck = QtGui.QCheckBox(self.groupBox_2)
        self.chkSpellCheck.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSpellCheck.sizePolicy().hasHeightForWidth())
        self.chkSpellCheck.setSizePolicy(sizePolicy)
        self.chkSpellCheck.setText(QtGui.QApplication.translate("SettingsMenu", "Enable spell-checking", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSpellCheck.setChecked(True)
        self.chkSpellCheck.setObjectName(_fromUtf8("chkSpellCheck"))
        self.horizontalLayout.addWidget(self.chkSpellCheck)
        self.cboSpellCheckLang = QtGui.QComboBox(self.groupBox_2)
        self.cboSpellCheckLang.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSpellCheckLang.sizePolicy().hasHeightForWidth())
        self.cboSpellCheckLang.setSizePolicy(sizePolicy)
        self.cboSpellCheckLang.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboSpellCheckLang.setObjectName(_fromUtf8("cboSpellCheckLang"))
        self.cboSpellCheckLang.addItem(_fromUtf8(""))
        self.cboSpellCheckLang.setItemText(0, QtGui.QApplication.translate("SettingsMenu", "English (US)", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSpellCheckLang.addItem(_fromUtf8(""))
        self.cboSpellCheckLang.setItemText(1, QtGui.QApplication.translate("SettingsMenu", "English (UK)", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.cboSpellCheckLang)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.chkTextRepl = QtGui.QCheckBox(self.groupBox_2)
        self.chkTextRepl.setEnabled(False)
        self.chkTextRepl.setText(QtGui.QApplication.translate("SettingsMenu", "Enable automatic text replacement", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTextRepl.setObjectName(_fromUtf8("chkTextRepl"))
        self.verticalLayout_9.addWidget(self.chkTextRepl)
        self.chkSmartQuotes = QtGui.QCheckBox(self.groupBox_2)
        self.chkSmartQuotes.setEnabled(False)
        self.chkSmartQuotes.setText(QtGui.QApplication.translate("SettingsMenu", "Enable smart quotes", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSmartQuotes.setObjectName(_fromUtf8("chkSmartQuotes"))
        self.verticalLayout_9.addWidget(self.chkSmartQuotes)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.chkTagHighlight = QtGui.QCheckBox(self.groupBox_2)
        self.chkTagHighlight.setEnabled(False)
        self.chkTagHighlight.setText(QtGui.QApplication.translate("SettingsMenu", "Enable tag highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTagHighlight.setObjectName(_fromUtf8("chkTagHighlight"))
        self.verticalLayout_8.addWidget(self.chkTagHighlight)
        self.chkTermHighlight = QtGui.QCheckBox(self.groupBox_2)
        self.chkTermHighlight.setText(QtGui.QApplication.translate("SettingsMenu", "Enable terminology highlighting", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTermHighlight.setChecked(True)
        self.chkTermHighlight.setObjectName(_fromUtf8("chkTermHighlight"))
        self.verticalLayout_8.addWidget(self.chkTermHighlight)
        self.chkMangle = QtGui.QCheckBox(self.groupBox_2)
        self.chkMangle.setText(QtGui.QApplication.translate("SettingsMenu", "Enforce game\'s text rendering limitations", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMangle.setChecked(True)
        self.chkMangle.setObjectName(_fromUtf8("chkMangle"))
        self.verticalLayout_8.addWidget(self.chkMangle)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SettingsMenu", "Building", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setContentsMargins(-1, 4, -1, 8)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkPackUmdimage = QtGui.QCheckBox(self.groupBox_4)
        self.chkPackUmdimage.setText(QtGui.QApplication.translate("SettingsMenu", "Repack umdimage", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPackUmdimage.setChecked(True)
        self.chkPackUmdimage.setObjectName(_fromUtf8("chkPackUmdimage"))
        self.horizontalLayout_6.addWidget(self.chkPackUmdimage)
        self.chkPackUmdimage2 = QtGui.QCheckBox(self.groupBox_4)
        self.chkPackUmdimage2.setText(QtGui.QApplication.translate("SettingsMenu", "Repack umdimage2", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPackUmdimage2.setChecked(True)
        self.chkPackUmdimage2.setObjectName(_fromUtf8("chkPackUmdimage2"))
        self.horizontalLayout_6.addWidget(self.chkPackUmdimage2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabPrefs)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsMenu", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setContentsMargins(-1, 4, -1, 8)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.chkExpandTrees = QtGui.QCheckBox(self.groupBox_3)
        self.chkExpandTrees.setText(QtGui.QApplication.translate("SettingsMenu", "Automatically expand similarity trees", None, QtGui.QApplication.UnicodeUTF8))
        self.chkExpandTrees.setChecked(True)
        self.chkExpandTrees.setObjectName(_fromUtf8("chkExpandTrees"))
        self.verticalLayout_7.addWidget(self.chkExpandTrees)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.tabPrefs, _fromUtf8(""))
        self.tabLocs = QtGui.QWidget()
        self.tabLocs.setObjectName(_fromUtf8("tabLocs"))
        self.gridLayout = QtGui.QGridLayout(self.tabLocs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tabLocs)
        self.label.setText(QtGui.QApplication.translate("SettingsMenu", "ISO directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.txtIsoDir = QtGui.QLineEdit(self.tabLocs)
        self.txtIsoDir.setObjectName(_fromUtf8("txtIsoDir"))
        self.gridLayout.addWidget(self.txtIsoDir, 1, 1, 1, 1)
        self.btnIsoDir = QtGui.QPushButton(self.tabLocs)
        self.btnIsoDir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIsoDir.setObjectName(_fromUtf8("btnIsoDir"))
        self.gridLayout.addWidget(self.btnIsoDir, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabLocs)
        self.label_2.setText(QtGui.QApplication.translate("SettingsMenu", "ISO file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.txtIsoFile = QtGui.QLineEdit(self.tabLocs)
        self.txtIsoFile.setObjectName(_fromUtf8("txtIsoFile"))
        self.gridLayout.addWidget(self.txtIsoFile, 2, 1, 1, 1)
        self.btnIsoFile = QtGui.QPushButton(self.tabLocs)
        self.btnIsoFile.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIsoFile.setObjectName(_fromUtf8("btnIsoFile"))
        self.gridLayout.addWidget(self.btnIsoFile, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabLocs)
        self.label_3.setText(QtGui.QApplication.translate("SettingsMenu", "umdimage directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.txtUmdDir = QtGui.QLineEdit(self.tabLocs)
        self.txtUmdDir.setObjectName(_fromUtf8("txtUmdDir"))
        self.gridLayout.addWidget(self.txtUmdDir, 3, 1, 1, 1)
        self.btnUmdDir = QtGui.QPushButton(self.tabLocs)
        self.btnUmdDir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUmdDir.setObjectName(_fromUtf8("btnUmdDir"))
        self.gridLayout.addWidget(self.btnUmdDir, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabLocs)
        self.label_4.setText(QtGui.QApplication.translate("SettingsMenu", "umdimage2 directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.txtUmd2Dir = QtGui.QLineEdit(self.tabLocs)
        self.txtUmd2Dir.setObjectName(_fromUtf8("txtUmd2Dir"))
        self.gridLayout.addWidget(self.txtUmd2Dir, 4, 1, 1, 1)
        self.btnUmd2Dir = QtGui.QPushButton(self.tabLocs)
        self.btnUmd2Dir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUmd2Dir.setObjectName(_fromUtf8("btnUmd2Dir"))
        self.gridLayout.addWidget(self.btnUmd2Dir, 4, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tabLocs)
        self.label_10.setText(QtGui.QApplication.translate("SettingsMenu", "!toc.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.txtToc = QtGui.QLineEdit(self.tabLocs)
        self.txtToc.setObjectName(_fromUtf8("txtToc"))
        self.gridLayout.addWidget(self.txtToc, 6, 1, 1, 1)
        self.btnToc = QtGui.QPushButton(self.tabLocs)
        self.btnToc.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnToc.setObjectName(_fromUtf8("btnToc"))
        self.gridLayout.addWidget(self.btnToc, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabLocs)
        self.label_11.setText(QtGui.QApplication.translate("SettingsMenu", "!toc2.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.txtToc2 = QtGui.QLineEdit(self.tabLocs)
        self.txtToc2.setObjectName(_fromUtf8("txtToc2"))
        self.gridLayout.addWidget(self.txtToc2, 7, 1, 1, 1)
        self.btnToc2 = QtGui.QPushButton(self.tabLocs)
        self.btnToc2.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnToc2.setObjectName(_fromUtf8("btnToc2"))
        self.gridLayout.addWidget(self.btnToc2, 7, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tabLocs)
        self.label_7.setText(QtGui.QApplication.translate("SettingsMenu", "Voice directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 1)
        self.txtVoice = QtGui.QLineEdit(self.tabLocs)
        self.txtVoice.setObjectName(_fromUtf8("txtVoice"))
        self.gridLayout.addWidget(self.txtVoice, 10, 1, 1, 1)
        self.btnVoice = QtGui.QPushButton(self.tabLocs)
        self.btnVoice.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoice.setObjectName(_fromUtf8("btnVoice"))
        self.gridLayout.addWidget(self.btnVoice, 10, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabLocs)
        self.label_8.setText(QtGui.QApplication.translate("SettingsMenu", "Copy changes to...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 12, 0, 1, 1)
        self.txtCopy = QtGui.QLineEdit(self.tabLocs)
        self.txtCopy.setObjectName(_fromUtf8("txtCopy"))
        self.gridLayout.addWidget(self.txtCopy, 12, 1, 1, 1)
        self.btnCopy = QtGui.QPushButton(self.tabLocs)
        self.btnCopy.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCopy.setObjectName(_fromUtf8("btnCopy"))
        self.gridLayout.addWidget(self.btnCopy, 12, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.tabLocs)
        self.label_9.setText(QtGui.QApplication.translate("SettingsMenu", "Make backup to...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 13, 0, 1, 1)
        self.txtBackup = QtGui.QLineEdit(self.tabLocs)
        self.txtBackup.setObjectName(_fromUtf8("txtBackup"))
        self.gridLayout.addWidget(self.txtBackup, 13, 1, 1, 1)
        self.btnBackup = QtGui.QPushButton(self.tabLocs)
        self.btnBackup.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBackup.setObjectName(_fromUtf8("btnBackup"))
        self.gridLayout.addWidget(self.btnBackup, 13, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabLocs)
        self.label_6.setText(QtGui.QApplication.translate("SettingsMenu", "Editor GFX directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.txtGFXDir = QtGui.QLineEdit(self.tabLocs)
        self.txtGFXDir.setObjectName(_fromUtf8("txtGFXDir"))
        self.gridLayout.addWidget(self.txtGFXDir, 9, 1, 1, 1)
        self.btnGFXDir = QtGui.QPushButton(self.tabLocs)
        self.btnGFXDir.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGFXDir.setObjectName(_fromUtf8("btnGFXDir"))
        self.gridLayout.addWidget(self.btnGFXDir, 9, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tabLocs)
        self.label_5.setText(QtGui.QApplication.translate("SettingsMenu", "Terminology csv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 11, 0, 1, 1)
        self.txtTerminology = QtGui.QLineEdit(self.tabLocs)
        self.txtTerminology.setObjectName(_fromUtf8("txtTerminology"))
        self.gridLayout.addWidget(self.txtTerminology, 11, 1, 1, 1)
        self.btnTerminology = QtGui.QPushButton(self.tabLocs)
        self.btnTerminology.setText(QtGui.QApplication.translate("SettingsMenu", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTerminology.setObjectName(_fromUtf8("btnTerminology"))
        self.gridLayout.addWidget(self.btnTerminology, 11, 2, 1, 1)
        self.tabWidget.addTab(self.tabLocs, _fromUtf8(""))
        self.tabTags = QtGui.QWidget()
        self.tabTags.setObjectName(_fromUtf8("tabTags"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabTags)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeTags = QtGui.QTreeWidget(self.tabTags)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeTags.sizePolicy().hasHeightForWidth())
        self.treeTags.setSizePolicy(sizePolicy)
        self.treeTags.setAlternatingRowColors(True)
        self.treeTags.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.treeTags.setIndentation(0)
        self.treeTags.setRootIsDecorated(False)
        self.treeTags.setUniformRowHeights(True)
        self.treeTags.setItemsExpandable(False)
        self.treeTags.setAllColumnsShowFocus(True)
        self.treeTags.setHeaderHidden(False)
        self.treeTags.setExpandsOnDoubleClick(False)
        self.treeTags.setColumnCount(2)
        self.treeTags.setObjectName(_fromUtf8("treeTags"))
        self.treeTags.headerItem().setText(0, QtGui.QApplication.translate("SettingsMenu", "Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTags.headerItem().setText(1, QtGui.QApplication.translate("SettingsMenu", "Highlight", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeTags)
        self.treeTags.topLevelItem(0).setText(0, QtGui.QApplication.translate("SettingsMenu", "fuckthis", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        self.treeTags.topLevelItem(0).setText(1, QtGui.QApplication.translate("SettingsMenu", "#C86260", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(200, 98, 96))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeTags)
        self.treeTags.topLevelItem(1).setText(0, QtGui.QApplication.translate("SettingsMenu", "iffy", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTags.topLevelItem(1).setText(1, QtGui.QApplication.translate("SettingsMenu", "#99D9EA", None, QtGui.QApplication.UnicodeUTF8))
        brush = QtGui.QBrush(QtGui.QColor(153, 217, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(1, brush)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeTags.header().setCascadingSectionResizes(True)
        self.treeTags.header().setDefaultSectionSize(200)
        self.treeTags.header().setHighlightSections(False)
        self.treeTags.header().setSortIndicatorShown(False)
        self.treeTags.header().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.treeTags)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnNewTag = QtGui.QPushButton(self.tabTags)
        self.btnNewTag.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewTag.setIcon(icon1)
        self.btnNewTag.setObjectName(_fromUtf8("btnNewTag"))
        self.horizontalLayout_4.addWidget(self.btnNewTag)
        self.btnDelTag = QtGui.QPushButton(self.tabTags)
        self.btnDelTag.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelTag.setIcon(icon2)
        self.btnDelTag.setObjectName(_fromUtf8("btnDelTag"))
        self.horizontalLayout_4.addWidget(self.btnDelTag)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btnTagToTop = QtGui.QPushButton(self.tabTags)
        self.btnTagToTop.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagToTop.setIcon(icon3)
        self.btnTagToTop.setObjectName(_fromUtf8("btnTagToTop"))
        self.horizontalLayout_4.addWidget(self.btnTagToTop)
        self.btnTagUp = QtGui.QPushButton(self.tabTags)
        self.btnTagUp.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagUp.setIcon(icon4)
        self.btnTagUp.setObjectName(_fromUtf8("btnTagUp"))
        self.horizontalLayout_4.addWidget(self.btnTagUp)
        self.btnTagDown = QtGui.QPushButton(self.tabTags)
        self.btnTagDown.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagDown.setIcon(icon5)
        self.btnTagDown.setObjectName(_fromUtf8("btnTagDown"))
        self.horizontalLayout_4.addWidget(self.btnTagDown)
        self.btnTagToBottom = QtGui.QPushButton(self.tabTags)
        self.btnTagToBottom.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/resultset_last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTagToBottom.setIcon(icon6)
        self.btnTagToBottom.setObjectName(_fromUtf8("btnTagToBottom"))
        self.horizontalLayout_4.addWidget(self.btnTagToBottom)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tabTags, _fromUtf8(""))
        self.tabRepl = QtGui.QWidget()
        self.tabRepl.setObjectName(_fromUtf8("tabRepl"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabRepl)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.treeTextRepl = QtGui.QTreeWidget(self.tabRepl)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeTextRepl.sizePolicy().hasHeightForWidth())
        self.treeTextRepl.setSizePolicy(sizePolicy)
        self.treeTextRepl.setAlternatingRowColors(True)
        self.treeTextRepl.setIndentation(0)
        self.treeTextRepl.setRootIsDecorated(False)
        self.treeTextRepl.setUniformRowHeights(True)
        self.treeTextRepl.setItemsExpandable(False)
        self.treeTextRepl.setAllColumnsShowFocus(True)
        self.treeTextRepl.setHeaderHidden(False)
        self.treeTextRepl.setExpandsOnDoubleClick(False)
        self.treeTextRepl.setColumnCount(2)
        self.treeTextRepl.setObjectName(_fromUtf8("treeTextRepl"))
        self.treeTextRepl.headerItem().setText(0, QtGui.QApplication.translate("SettingsMenu", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.headerItem().setText(1, QtGui.QApplication.translate("SettingsMenu", "Replace with", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.treeTextRepl)
        self.treeTextRepl.topLevelItem(0).setText(0, QtGui.QApplication.translate("SettingsMenu", "—-", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.topLevelItem(0).setText(1, QtGui.QApplication.translate("SettingsMenu", "–", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeTextRepl)
        self.treeTextRepl.topLevelItem(1).setText(0, QtGui.QApplication.translate("SettingsMenu", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.topLevelItem(1).setText(1, QtGui.QApplication.translate("SettingsMenu", "—", None, QtGui.QApplication.UnicodeUTF8))
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeTextRepl.header().setCascadingSectionResizes(True)
        self.treeTextRepl.header().setDefaultSectionSize(200)
        self.treeTextRepl.header().setHighlightSections(False)
        self.treeTextRepl.header().setSortIndicatorShown(True)
        self.treeTextRepl.header().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.treeTextRepl)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnNewRepl = QtGui.QPushButton(self.tabRepl)
        self.btnNewRepl.setText(_fromUtf8(""))
        self.btnNewRepl.setIcon(icon1)
        self.btnNewRepl.setObjectName(_fromUtf8("btnNewRepl"))
        self.horizontalLayout_5.addWidget(self.btnNewRepl)
        self.btnDelRepl = QtGui.QPushButton(self.tabRepl)
        self.btnDelRepl.setText(_fromUtf8(""))
        self.btnDelRepl.setIcon(icon2)
        self.btnDelRepl.setObjectName(_fromUtf8("btnDelRepl"))
        self.horizontalLayout_5.addWidget(self.btnDelRepl)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tabRepl, _fromUtf8(""))
        self.tabHacks = QtGui.QWidget()
        self.tabHacks.setObjectName(_fromUtf8("tabHacks"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabHacks)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lstHacks = QtGui.QListWidget(self.tabHacks)
        self.lstHacks.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lstHacks.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.lstHacks.setViewMode(QtGui.QListView.ListMode)
        self.lstHacks.setObjectName(_fromUtf8("lstHacks"))
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Swap O/X Buttons", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Map Name Centering", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Names)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Line Length)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Ammo/Present Menu (Previews)", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Long Ammo File Fix", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Checked)
        self.lstHacks.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setText(QtGui.QApplication.translate("SettingsMenu", "Fix Glyph Height", None, QtGui.QApplication.UnicodeUTF8))
        item.setCheckState(QtCore.Qt.Unchecked)
        self.lstHacks.addItem(item)
        self.verticalLayout_2.addWidget(self.lstHacks)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.tabHacks)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("margin-bottom: 1px;"))
        self.label_12.setText(QtGui.QApplication.translate("SettingsMenu", "System Menu Language", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.cboHackLang = QtGui.QComboBox(self.tabHacks)
        self.cboHackLang.setObjectName(_fromUtf8("cboHackLang"))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(0, QtGui.QApplication.translate("SettingsMenu", "Japanese", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(1, QtGui.QApplication.translate("SettingsMenu", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(2, QtGui.QApplication.translate("SettingsMenu", "French", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(3, QtGui.QApplication.translate("SettingsMenu", "Spanish", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(4, QtGui.QApplication.translate("SettingsMenu", "German", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(5, QtGui.QApplication.translate("SettingsMenu", "Italian", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(6, QtGui.QApplication.translate("SettingsMenu", "Dutch", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(7, QtGui.QApplication.translate("SettingsMenu", "Portuguese", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(8, QtGui.QApplication.translate("SettingsMenu", "Russian", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(9, QtGui.QApplication.translate("SettingsMenu", "Korean", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(10, QtGui.QApplication.translate("SettingsMenu", "Traditional Chinese", None, QtGui.QApplication.UnicodeUTF8))
        self.cboHackLang.addItem(_fromUtf8(""))
        self.cboHackLang.setItemText(11, QtGui.QApplication.translate("SettingsMenu", "Simplified Chinese", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.cboHackLang)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.btnReloadHacks = QtGui.QPushButton(self.tabHacks)
        self.btnReloadHacks.setText(QtGui.QApplication.translate("SettingsMenu", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReloadHacks.setIcon(icon7)
        self.btnReloadHacks.setObjectName(_fromUtf8("btnReloadHacks"))
        self.horizontalLayout_2.addWidget(self.btnReloadHacks)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabHacks, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsMenu)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsMenu.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsMenu.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsMenu)
        SettingsMenu.setTabOrder(self.txtIsoDir, self.btnIsoDir)
        SettingsMenu.setTabOrder(self.btnIsoDir, self.txtIsoFile)
        SettingsMenu.setTabOrder(self.txtIsoFile, self.btnIsoFile)
        SettingsMenu.setTabOrder(self.btnIsoFile, self.txtUmdDir)
        SettingsMenu.setTabOrder(self.txtUmdDir, self.btnUmdDir)
        SettingsMenu.setTabOrder(self.btnUmdDir, self.txtUmd2Dir)
        SettingsMenu.setTabOrder(self.txtUmd2Dir, self.btnUmd2Dir)
        SettingsMenu.setTabOrder(self.btnUmd2Dir, self.txtToc)
        SettingsMenu.setTabOrder(self.txtToc, self.btnToc)
        SettingsMenu.setTabOrder(self.btnToc, self.txtToc2)
        SettingsMenu.setTabOrder(self.txtToc2, self.btnToc2)
        SettingsMenu.setTabOrder(self.btnToc2, self.txtVoice)
        SettingsMenu.setTabOrder(self.txtVoice, self.btnVoice)
        SettingsMenu.setTabOrder(self.btnVoice, self.txtCopy)
        SettingsMenu.setTabOrder(self.txtCopy, self.btnCopy)
        SettingsMenu.setTabOrder(self.btnCopy, self.txtBackup)
        SettingsMenu.setTabOrder(self.txtBackup, self.btnBackup)

    def retranslateUi(self, SettingsMenu):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPrefs), QtGui.QApplication.translate("SettingsMenu", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLocs), QtGui.QApplication.translate("SettingsMenu", "File Locations", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeTags.isSortingEnabled()
        self.treeTags.setSortingEnabled(False)
        self.treeTags.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTags), QtGui.QApplication.translate("SettingsMenu", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.treeTextRepl.setSortingEnabled(True)
        __sortingEnabled = self.treeTextRepl.isSortingEnabled()
        self.treeTextRepl.setSortingEnabled(False)
        self.treeTextRepl.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRepl), QtGui.QApplication.translate("SettingsMenu", "Text Replacement", None, QtGui.QApplication.UnicodeUTF8))
        self.lstHacks.setSortingEnabled(False)
        __sortingEnabled = self.lstHacks.isSortingEnabled()
        self.lstHacks.setSortingEnabled(False)
        item = self.lstHacks.item(0)
        item = self.lstHacks.item(1)
        item = self.lstHacks.item(2)
        item = self.lstHacks.item(3)
        item = self.lstHacks.item(4)
        item = self.lstHacks.item(5)
        item = self.lstHacks.item(6)
        self.lstHacks.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHacks), QtGui.QApplication.translate("SettingsMenu", "Hacks", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
